type_map = {
    'CC' :'Coordinating conjunction',
    'CD' :'Cardinal number',
    'DT' :'Determiner',
    'EX' :'Existential there',
    'FW' :'Foreign word',
    'IN' :'Preposition or subordinating conjunction',
    'JJ' :'Adjective',
    'JJR' :'Adjective, comparative',
    'JJS' :'Adjective, superlative',
    'LS' :'List item marker',
    'MD' :'Modal',
    'NN' :'Noun, singular or mass',
    'NNS' :'Noun, plural',
    'NNP' :'Proper noun, singular',
    'NNPS' :'Proper noun, plural',
    'PDT' :'Predeterminer',
    'POS' :'Possessive ending',
    'PRP' :'Personal pronoun',
    'PRP$':'Possessive pronoun',
    'RB' :'Adverb',
    'RBR' :'Adverb, comparative',
    'RBS' :'Adverb, superlative',
    'RP' :'Particle',
    'SYM' :'Symbol',
    'TO' :'to',
    'UH' :'Interjection',
    'VB' :'Verb, base form',
    'VBD' :'Verb, past tense',
    'VBG' :'Verb, gerund or present participle',
    'VBN' :'Verb, past participle',
    'VBP' :'Verb, non-3rd person singular present',
    'VBZ' :'Verb, 3rd person singular present',
    'WDT' :'Wh-determiner',
    'WP' :'Wh-pronoun',
    'WP$':'Possessive wh-pronoun',
    'WRB' :'Wh-adverb',
    '.': 'Puncuation',
}


noun = {
    'antsn':"Antonyms",
    'hypen':"Hypernyms",
    'hypon':"Hyponyms & Hyponym Tree",
    'treen':"Hyponyms & Hyponym Tree",
    'synsn':"Synonyms (ordered by estimated frequency)",
    'attrn':"Attributes",
    'derin':"Derived Forms",
    'domnn':"Domain",
    'famln':"Familiarity & Polysemy Count",
    'coorn':"Coordinate Terms (sisters)",
    'grepn':"List of Compound Words",
    'over':"Overview of Senses",
}

verb = {
    'antsv':"Antonyms",
    'hypev':"Hypernyms",
    'hypov':"Hyponyms & Hyponym Tree",
    'treev':"Hyponyms & Hyponym Tree",
    'synsv':"Synonyms (ordered by estimated frequency)",
    'deriv':"Derived Forms",
    'famlv':"Familiarity & Polysemy Count",
    'framv':"Verb Frames",
    'coorv':"Coordinate Terms (sisters)",
    'simsv':"Synonyms (grouped by similarity of meaning)",
    'grepv':"List of Compound Words",
    'over':"Overview of Senses",
}

adj = {
    'antsa':"Antonyms",
    'synsa':"Synonyms (ordered by estimated frequency)",
    'domna':"Domain",
    'famla':"Familiarity & Polysemy Count",
    'grepa':"List of Compound Words",
    'over':"Overview of Senses",
}

attrs = {
    'h':'Print help text before search results.',
    'g':'Display textual glosses associated with synsets.',
    'a':'Display lexicographer file information.',
    'o':'Display synset offset of each synset.',
    's':'Display each word\'s sense numbers in synsets',
    'l':'Display the WordNet copyright notice, version number, and license.',
    'n#':'Perform search on sense number # only.',
    'over':'Display overview of all senses of searchstr in all syntactic categories.',
}
