# Generated by Django 2.2.3 on 2019-07-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Input data as a start value.')),
            ],
        ),
        migrations.CreateModel(
            name='TemporalSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.ManyToManyField(to='first.TemporalInput')),
            ],
        ),
    ]
