# Generated by Django 2.2.3 on 2019-07-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporalinput',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
