# Generated by Django 2.2.3 on 2019-07-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20190727_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporalinput',
            name='tokens',
        ),
        migrations.AddField(
            model_name='temporalinput',
            name='tokens',
            field=models.ManyToManyField(to='first.PositionTokenWord'),
        ),
    ]
