# Generated by Django 2.2.3 on 2019-07-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20190727_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenword',
            name='dictionary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporalinput',
            name='tokens',
            field=models.ManyToManyField(blank=True, to='first.PositionTokenWord'),
        ),
    ]
