# Generated by Django 2.2.3 on 2019-07-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20190728_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenword',
            old_name='dictionary',
            new_name='raw_dictionary',
        ),
    ]
