# Generated by Django 2.2.3 on 2019-07-27 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20190728_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinitionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DefinitionValueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='first.DefinitionType')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='first.DefinitionValueType')),
            ],
        ),
        migrations.AddField(
            model_name='tokenword',
            name='dictionary',
            field=models.ManyToManyField(to='first.Definition'),
        ),
    ]
