type_map = {
    'CC' :'Coordinating conjunction',
    'CD' :'Cardinal number',
    'DT' :'Determiner',
    'EX' :'Existential there',
    'FW' :'Foreign word',
    'IN' :'Preposition or subordinating conjunction',
    'JJ' :'Adjective',
    'JJR' :'Adjective, comparative',
    'JJS' :'Adjective, superlative',
    'LS' :'List item marker',
    'MD' :'Modal',
    'NN' :'Noun, singular or mass',
    'NNS' :'Noun, plural',
    'NNP' :'Proper noun, singular',
    'NNPS' :'Proper noun, plural',
    'PDT' :'Predeterminer',
    'POS' :'Possessive ending',
    'PRP' :'Personal pronoun',
    'PRP$':'Possessive pronoun',
    'RB' :'Adverb',
    'RBR' :'Adverb, comparative',
    'RBS' :'Adverb, superlative',
    'RP' :'Particle',
    'SYM' :'Symbol',
    'TO' :'to',
    'UH' :'Interjection',
    'VB' :'Verb, base form',
    'VBD' :'Verb, past tense',
    'VBG' :'Verb, gerund or present participle',
    'VBN' :'Verb, past participle',
    'VBP' :'Verb, non-3rd person singular present',
    'VBZ' :'Verb, 3rd person singular present',
    'WDT' :'Wh-determiner',
    'WP' :'Wh-pronoun',
    'WP$':'Possessive wh-pronoun',
    'WRB' :'Wh-adverb',
    '.': 'Puncuation',
}


simplify = {
    'verb': ['VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ',],
    'pronoun': ['PRP' , 'PRP$', 'WP' , 'WP$',],
    'adjective': ['JJ', 'JJR', 'JJS', ],
    'noun': ['NN', 'NNS', 'NNP', 'NNPS'],
}



noun = {
    'antsn':"Antonyms",
    'hypen':"Hypernyms",
    'hypon':"Hyponyms & Hyponym Tree",
    'treen':"Hyponyms & Hyponym Tree",
    'synsn':"Synonyms (ordered by estimated frequency)",
    'attrn':"Attributes",
    'derin':"Derived Forms",
    'domnn':"Domain",
    'famln':"Familiarity & Polysemy Count",
    'coorn':"Coordinate Terms (sisters)",
    'grepn':"List of Compound Words",
    'over':"Overview of Senses",
}

verb = {
    'antsv':"Antonyms",
    'hypev':"Hypernyms",
    'hypov':"Hyponyms & Hyponym Tree",
    'treev':"Hyponyms & Hyponym Tree",
    'synsv':"Synonyms (ordered by estimated frequency)",
    'deriv':"Derived Forms",
    'famlv':"Familiarity & Polysemy Count",
    'framv':"Verb Frames",
    'coorv':"Coordinate Terms (sisters)",
    'simsv':"Synonyms (grouped by similarity of meaning)",
    'grepv':"List of Compound Words",
    'over':"Overview of Senses",
}

adj = {
    'antsa':"Antonyms",
    'synsa':"Synonyms (ordered by estimated frequency)",
    'domna':"Domain",
    'famla':"Familiarity & Polysemy Count",
    'grepa':"List of Compound Words",
    'over':"Overview of Senses",
}

attrs = {
    'h':'Print help text before search results.',
    'g':'Display textual glosses associated with synsets.',
    'a':'Display lexicographer file information.',
    'o':'Display synset offset of each synset.',
    's':'Display each word\'s sense numbers in synsets',
    'l':'Display the WordNet copyright notice, version number, and license.',
    'n#':'Perform search on sense number # only.',
    'over':'Display overview of all senses of searchstr in all syntactic categories.',
}


REL_HEADINGS = {
    'en': {
        '/r/SimilarTo': ['Similar terms'],
        '/r/RelatedTo': ['Related terms'],
        '/r/Synonym': ['Synonyms'],
        '/r/Antonym': ['Antonyms'],
        '/r/FormOf': ['Word forms', 'Root words'],
        '/r/HasContext': ['Terms with this context', 'Context of this term'],
        '/r/DerivedFrom': ['Derived terms', 'Derived from'],
        '/r/IsA': ['Types of {0}', '{0} is a type of...'],
        '/r/EtymologicallyRelatedTo': ['Etymologically related'],
        '/r/AtLocation': ['Things located at {0}', 'Location of {0}'],
        '/r/Causes': ['Causes of {0}', 'Effects of {0}'],
        '/r/UsedFor': ['Things used for {0}', '{0} is used for...'],
        '/r/NotUsedFor': ['Things that are not used for {0}', '{0} is not used for...'],
        '/r/MotivatedByGoal': ['Things motivated by {0}', '{0} is motivated by...'],
        '/r/HasSubevent': ['Subevents of {0}', '{0} is a subevent of...'],
        '/r/DistinctFrom': ['Distinct terms'],
        '/r/CapableOf': ['Things capable of {0}', '{0} is capable of...'],
        '/r/NotCapableOf': ['Things incapable of {0}', '{0} is not capable of...'],
        '/r/Desires': ['Things that want {0}', '{0} wants...'],
        '/r/NotDesires': ["Things that don't want {0}", "{0} doesn't want..."],
        '/r/PartOf': ['Parts of {0}', '{0} is part of...'],
        '/r/HasPrerequisite': ['Things that require {0}', '{0} requires...'],
        '/r/CausesDesire': ['Things that make you want {0}', '{0} makes you want...'],
        '/r/HasProperty': ['Things with the property {0}', 'Properties of {0}'],
        '/r/MadeOf': ['Things made of {0}', '{0} is made of...'],
        '/r/HasFirstSubevent': ['Things whose first step is {0}', '{0} is the first step of...'],
        '/r/HasLastSubevent': ['Things whose last step is {0}', '{0} is the last step of...'],
        '/r/DefinedAs': ['Things defined as {0}', '{0} is defined as...'],
        '/r/ReceivesAction': ['Things that can be {0}', '{0} can be...'],
        '/r/HasA': ['Things with {0}', '{0} has...'],
        '/r/SymbolOf': ['Symbols of {0}', '{0} symbolizes...'],
        '/r/ObstructedBy': ['{0} obstructs...', '{0} is obstructed by...'],
        '/r/Entails': ['Things that entail {0}', '{0} entails...'],
        '/r/CreatedBy': ['Things created by {0}', '{0} is created by...'],
        '/r/MannerOf': ['Ways of {0}', '{0} is a way of...'],
        '/r/LocationOfAction': ['Places where {0} happens', '{0} happens at...'],
        '/r/Uses': ['Things that use {0}', '{0} uses...'],
        '/r/ControlledBy': ['{0} controls...', '{0} is controlled by...'],
        '/r/LocatedNear': ['Things located near {0}', '{0} is near...'],
        '/r/ExternalURL': ['Links to ConceptNet', 'Links to other sites'],
    }
}
